'\" t
.\" This file is part of libsmack
.\" Copyright (C) 2012 Intel Corporation
.\"
.\" This library is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU Lesser General Public License
.\" version 2.1 as published by the Free Software Foundation.
.\"
.\" This library is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
.\" Lesser General Public License for more details.
.\"
.\" You should have received a copy of the GNU Lesser General Public
.\" License along with this library; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
.\" 02110-1301 USA
.\"
.\" Author:
.\" Brian McGillion <brian.mcgillion@intel.com>
.\"
.TH "SMACKCTL" "8" "03/05/2012" "smack-utils 1\&.0"
.SH NAME
smackctl \- Load and unload the system Smack rules files
.SH SYNOPSIS
.B smackctl ['apply'] ['clear'] ['status']

.SH DESCRIPTION
.B smackctl
is a program to load and unload the Smack context configurations.  It is generally called by an init process on startup and shutdown of the system when it is needed to change the Smack rules in the kernel.  The Smack system configuration files are all store in see FILES below.
.SH OPTIONS
.IP apply
Apply all the rules found in the configuration directory's
.IP clear
Remove all system rules from the kernel
.IP status
Show the status of the Smack system, specifically if /smack is mounted
.SH EXIT STATUS
On success
.B smackctl
returns 0 and 1 on failure.
.SH FILES
/smack
.br
/etc/smack/acceses.d
.br
/etc/smack/cipso.d
