'\" t
.\" This file is part of libsmack
.\" Copyright (C) 2012 Intel Corporation
.\"
.\" This library is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU Lesser General Public License
.\" version 2.1 as published by the Free Software Foundation.
.\"
.\" This library is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
.\" Lesser General Public License for more details.
.\"
.\" You should have received a copy of the GNU Lesser General Public
.\" License along with this library; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
.\" 02110-1301 USA
.\"
.\" Author:
.\" Brian McGillion <brian.mcgillion@intel.com>
.\"
.TH "SMACKD" "8" "07/05/2012" "smack-utils 1\&.0"
.SH NAME
smackd \- Experimental daemon to manage the Smack policy
.SH DESCRIPTION
.BR smackd ,
it is currently not recommended to use this process.
.SH SEE ALSO
.BR smackctl (8)
